### ISSUE TITLE
Extending an interface fails

### ISSUE THREAD

**Issue by BBosman** [YoloDev/babel-dts-generator#71]
Extending an interface bails during build with an `node.toCode is not a function` error.

This works:
```ts
interface Cancellable<T> {
  cancel: () => void;
  abort: () => void;
}
```

This doesn't:
```ts
interface CancellablePromise<T> extends Promise<T> {
  cancel: () => void;
  abort: () => void;
}
```

Full call stack:
```
TypeError: /Users/BBosman/Development/playground/dist/test.js: node.toCode is not a function
    at /Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/ast.js:1069:17
    at Array.map (<anonymous>)
    at Factory._toCode (/Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/ast.js:780:49)
    at Factory.toCode (/Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/ast.js:69:60)
    at /Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/ast.js:1069:17
    at Array.map (<anonymous>)
    at Factory._toCode (/Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/ast.js:169:66)
    at Factory.toCode (/Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/ast.js:69:60)
    at Factory.toString (/Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/ast.js:78:19)
    at generate (/Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/generators/index.js:31:17)
    at /Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/plugin.js:99:49
    at PluginPass.visit (/Users/BBosman/Development/playground/node_modules/babel-dts-generator/lib/plugin.js:27:12)
    at newFn (/Users/BBosman/Development/playground/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/BBosman/Development/playground/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/BBosman/Development/playground/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/BBosman/Development/playground/node_modules/babel-traverse/lib/path/context.js:117:8)
```

Hope you can help resolve this. If you need more info, let me know.

**Comment by Alxandr** [comment]
It's been a while since I've looked at this code, and even longer since I've used it. I can't guarantee that I will get to this anytime soon, unfortunately. Though, if you would like to take a stab at fixing it yourself, I would accept a PR.
